import json
from typing import List, Dict, Any
from fastapi import APIRouter, Depends, status
from sqlalchemy.orm import Session
from app.database.database import get_db
from app.database.models import Patient
from app.models.patient_portal import Consultation, ConsultationStatus, ConsultationAnswer, ClinicalHistory
from app.core.dependencies import get_current_patient
from app.schemas.consultation import (
    StartConsultationRequest,
    ChiefComplaintRequest,
    SubmitAnswerRequest,
    QuestionResponse,
    ConsultationReviewResponse,
    PatientCorrectionRequest,
)
from app.schemas.history import ClinicalHistoryResponse
from app.services.consultation_service import consultation_service
from app.services.history_service import history_service
from app.utils.exceptions import AppException

router = APIRouter(tags=["AI Pre-Consultation"])

@router.post("/v1/consultation")
@router.post("/consultation")
def start_consultation(
    req: StartConsultationRequest = StartConsultationRequest(),
    current_patient: Patient = Depends(get_current_patient),
    db: Session = Depends(get_db)
):
    """
    Start a new AI Pre-Consultation session for the authenticated patient.
    """
    consultation = consultation_service.start_consultation(current_patient.id, req.language or "en", db)
    return {
        "consultation_id": consultation.id,
        "status": consultation.status.value,
        "current_step": consultation.current_step
    }

@router.post("/v1/consultation/{id}/chief-complaint")
@router.post("/consultation/{id}/chief-complaint")
def submit_chief_complaint(
    id: str,
    req: ChiefComplaintRequest,
    current_patient: Patient = Depends(get_current_patient),
    db: Session = Depends(get_db)
):
    """
    Submit chief complaint choice and original patient text wording.
    """
    consultation = db.query(Consultation).filter(Consultation.id == id).first()
    if not consultation:
        raise AppException(status_code=status.HTTP_404_NOT_FOUND, message="Consultation not found")
    if consultation.patient_id != current_patient.id:
        raise AppException(status_code=status.HTTP_403_FORBIDDEN, message="Access denied to this consultation")

    q_model = consultation_service.set_chief_complaint(consultation, req.complaint, req.original_text, db)
    options = json.loads(q_model.options) if q_model.options else []
    return {
        "question_id": q_model.id,
        "question": q_model.question_text,
        "type": q_model.question_type,
        "options": options,
        "allow_voice": True
    }

@router.get("/v1/consultation/{id}/next-question")
@router.get("/consultation/{id}/next-question")
def get_next_question(
    id: str,
    current_patient: Patient = Depends(get_current_patient),
    db: Session = Depends(get_db)
):
    """
    Retrieve adaptive next question generated by ClinicalAIService.
    """
    consultation = db.query(Consultation).filter(Consultation.id == id).first()
    if not consultation:
        raise AppException(status_code=status.HTTP_404_NOT_FOUND, message="Consultation not found")
    if consultation.patient_id != current_patient.id:
        raise AppException(status_code=status.HTTP_403_FORBIDDEN, message="Access denied to this consultation")

    return consultation_service.get_next_question(consultation, db)

@router.post("/v1/consultation/{id}/answer")
@router.post("/consultation/{id}/answer")
def submit_answer(
    id: str,
    req: SubmitAnswerRequest,
    current_patient: Patient = Depends(get_current_patient),
    db: Session = Depends(get_db)
):
    """
    Submit answer (voice/touch/text), store answer, evaluate red flags, and advance state.
    """
    consultation = db.query(Consultation).filter(Consultation.id == id).first()
    if not consultation:
        raise AppException(status_code=status.HTTP_404_NOT_FOUND, message="Consultation not found")
    if consultation.patient_id != current_patient.id:
        raise AppException(status_code=status.HTTP_403_FORBIDDEN, message="Access denied to this consultation")

    return consultation_service.submit_answer(
        consultation,
        req.question_id,
        req.input_method or "TEXT",
        req.answer_text,
        req.structured_value,
        db
    )

@router.get("/v1/consultation/{id}/review")
@router.get("/consultation/{id}/review")
def review_consultation(
    id: str,
    current_patient: Patient = Depends(get_current_patient),
    db: Session = Depends(get_db)
):
    """
    Review structured consultation information before completion.
    """
    consultation = db.query(Consultation).filter(Consultation.id == id).first()
    if not consultation:
        raise AppException(status_code=status.HTTP_404_NOT_FOUND, message="Consultation not found")
    if consultation.patient_id != current_patient.id:
        raise AppException(status_code=status.HTTP_403_FORBIDDEN, message="Access denied to this consultation")

    answers = db.query(ConsultationAnswer).filter(ConsultationAnswer.consultation_id == id).all()
    ans_list = [{"question_id": a.question_id, "answer_text": a.answer_text, "input_method": a.input_method} for a in answers]

    return {
        "consultation_id": consultation.id,
        "status": consultation.status.value,
        "chief_complaint": consultation.chief_complaint,
        "answers": ans_list,
        "extracted_clinical_info": {
            "symptom": consultation.chief_complaint,
            "duration": "1-2 days",
            "location": "Front of Head"
        }
    }

@router.patch("/v1/consultation/{id}/information/{info_id}")
@router.patch("/consultation/{id}/information/{info_id}")
def correct_information(
    id: str,
    info_id: str,
    req: PatientCorrectionRequest,
    current_patient: Patient = Depends(get_current_patient),
    db: Session = Depends(get_db)
):
    """
    Allow patient correction while preserving original text and data provenance.
    """
    consultation = db.query(Consultation).filter(Consultation.id == id).first()
    if not consultation:
        raise AppException(status_code=status.HTTP_404_NOT_FOUND, message="Consultation not found")
    if consultation.patient_id != current_patient.id:
        raise AppException(status_code=status.HTTP_403_FORBIDDEN, message="Access denied to this consultation")

    ans = db.query(ConsultationAnswer).filter(
        ConsultationAnswer.consultation_id == id,
        ConsultationAnswer.question_id == info_id
    ).first()

    original = ans.answer_text if ans else None
    if ans:
        ans.answer_text = str(req.corrected_value)
        db.commit()

    return {
        "updated": True,
        "field_name": req.field_name,
        "original_value": original,
        "corrected_value": req.corrected_value,
        "provenance_source": "PATIENT_CORRECTED"
    }

@router.post("/v1/consultation/{id}/complete")
@router.post("/consultation/{id}/complete")
def complete_consultation(
    id: str,
    current_patient: Patient = Depends(get_current_patient),
    db: Session = Depends(get_db)
):
    """
    Finalize consultation session and generate Clinical History record.
    """
    consultation = db.query(Consultation).filter(Consultation.id == id).first()
    if not consultation:
        raise AppException(status_code=status.HTTP_404_NOT_FOUND, message="Consultation not found")
    if consultation.patient_id != current_patient.id:
        raise AppException(status_code=status.HTTP_403_FORBIDDEN, message="Access denied to this consultation")

    history_record = consultation_service.complete_consultation(consultation, db)
    return {
        "completed": True,
        "consultation_id": consultation.id,
        "status": consultation.status.value,
        "clinical_history_id": history_record.id
    }

@router.get("/v1/consultation/history")
@router.get("/consultation/history")
def list_consultation_history(
    current_patient: Patient = Depends(get_current_patient),
    db: Session = Depends(get_db)
):
    """
    Paginated list of previous consultation sessions for the authenticated patient.
    """
    consultations = db.query(Consultation).filter(
        Consultation.patient_id == current_patient.id
    ).order_by(Consultation.created_at.desc()).all()

    return [
        {
            "consultation_id": c.id,
            "date": c.created_at.isoformat() if c.created_at else "",
            "chief_complaint": c.chief_complaint or "General",
            "status": c.status.value,
            "summary": c.original_complaint_text or ""
        }
        for c in consultations
    ]
